name: Push image to Docker Hub

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag masden/ubuntu-odbc:18.04
    - uses: azure/docker-login@v1
      with:
        username: ${{secrets.DOCKER_LOGIN}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Push image to Docker Hub
      run: docker push masden/ubuntu-odbc:18.04
